export type University = {
  id: string;
  name: string;
  slug: string;
  city: string;
  state: string | null;
  country: string;
  latitude: number | null;
  longitude: number | null;
  website: string | null;
  logo_url: string | null;
  image_url: string | null;
  type: string | null;
  total_enrollment: number | null;
  undergraduate_enrollment: number | null;
  acceptance_rate: number | null;
  average_sat: number | null;
  average_act: number | null;
  application_deadline: string | null;
  application_fee: number | null;
  graduation_rate: number | null;
  retention_rate: number | null;
  student_faculty_ratio: number | null;
  tuition_in_state: number | null;
  tuition_out_state: number | null;
  room_and_board: number | null;
  books_supplies: number | null;
  avg_financial_aid: number | null;
  percent_receiving_aid: number | null;
  avg_net_price: number | null;
  us_news_rank: number | null;
  qs_world_rank: number | null;
  times_rank: number | null;
  forbes_rank: number | null;
  common_app: boolean | null;
  coalition_app: boolean | null;
  requires_essay: boolean | null;
  created_at: string;
  updated_at: string;
};

export type FilterState = {
  country: string;
  state: string;
  minTuition: number;
  maxTuition: number;
  minAcceptance: number;
  maxAcceptance: number;
  minEnrollment: number;
  maxEnrollment: number;
  type: string;
};
